server {
    listen 3000; # Nginx ascolta sulla porta indicata
    server_name homelab;

    root /usr/share/nginx/html;
    index index.html;

    location /incrementa {
        # 'backend' è il nome del servizio nel docker-compose.yml
        proxy_pass http://backend:8080; 
        
        # Queste righe servono per passare correttamente l'IP dell'utente al backend
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

#    location /grafana {
#	proxy_pass http://grafana:4000/;
#        proxy_set_header Host $host;
#        proxy_set_header X-Real-IP $remote_addr;
#    }
}
